import { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { Youtube, Settings2, Play, MessageSquare, Loader2, FileText, Send, Clock, Bot, Sparkles, FileDown, FileCode2 } from 'lucide-react';

import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../components/ui/select";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card";
import { ScrollArea } from "../components/ui/scroll-area";
import { Textarea } from "../components/ui/textarea";

const API_BASE = "http://localhost:8000/api";

function App() {
  // Form State
  const [url, setUrl] = useState('');
  const [provider, setProvider] = useState('gemini');
  const [whisperProvider, setWhisperProvider] = useState('local');
  const [groqApiKey, setGroqApiKey] = useState('');
  const [startTime, setStartTime] = useState('');
  const [endTime, setEndTime] = useState('');
  const [showSettings, setShowSettings] = useState(false);

  // Process State
  const [status, setStatus] = useState('idle'); // idle, processing, completed, error
  const [taskId, setTaskId] = useState(null);
  const [progress, setProgress] = useState('');

  // Result State
  const [notes, setNotes] = useState('');
  const [videoTitle, setVideoTitle] = useState('');
  const [videoDescription, setVideoDescription] = useState('');

  // Chat State
  const [chatMessages, setChatMessages] = useState([]);
  const [currentQuestion, setCurrentQuestion] = useState('');
  const [isChatting, setIsChatting] = useState(false);
  const chatEndRef = useRef(null);

  useEffect(() => {
    let interval;
    if (status === 'processing' && taskId) {
      interval = setInterval(async () => {
        try {
          const res = await axios.get(`${API_BASE}/status/${taskId}`);
          setProgress(res.data.progress);
          if (res.data.status === 'completed') {
            setStatus('completed');
            setNotes(res.data.notes);
            setVideoTitle(res.data.video_title);
            setVideoDescription(res.data.video_description);
            clearInterval(interval);
          } else if (res.data.status === 'error') {
            setStatus('error');
            setProgress(res.data.progress || 'An error occurred during processing.');
            clearInterval(interval);
          }
        } catch (error) {
          console.error("Polling error", error);
        }
      }, 2000);
    }
    return () => clearInterval(interval);
  }, [status, taskId]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  const downloadPDF = () => {
    const content = document.getElementById('notes-content').innerHTML;
    const printWindow = window.open('', '', 'height=800,width=800');
    if (!printWindow) {
      alert("Please allow popups to download the PDF.");
      return;
    }
    
    printWindow.document.write(`
      <html>
        <head>
          <title>${videoTitle || 'Notes'} - PDF Export</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; line-height: 1.6; color: #18181b; }
            h1, h2, h3, h4 { color: #09090b; margin-top: 1.5em; margin-bottom: 0.5em; font-weight: 600; }
            h1 { font-size: 2em; border-bottom: 2px solid #e4e4e7; padding-bottom: 0.3em; }
            h2 { font-size: 1.5em; border-bottom: 1px solid #e4e4e7; padding-bottom: 0.2em; }
            p, ul, ol { margin-bottom: 1em; }
            code { background-color: #f4f4f5; padding: 0.2em 0.4em; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
            pre { background-color: #18181b; color: #f4f4f5; padding: 1em; border-radius: 8px; overflow-x: auto; margin-bottom: 1em;}
            pre code { background-color: transparent; padding: 0; color: inherit; }
            blockquote { border-left: 4px solid #e4e4e7; padding-left: 1em; color: #71717a; margin: 0 0 1em 0; }
            @media print {
              body { padding: 0; }
              @page { margin: 2cm; }
            }
          </style>
        </head>
        <body>
          <h1>${videoTitle || 'Video Notes'}</h1>
          <p style="color: #71717a; font-size: 0.9em;"><em>${videoDescription ? videoDescription.substring(0, 150) + '...' : 'Generated by VideoNotes Agent'}</em></p>
          <hr style="border: 0; border-top: 1px solid #e4e4e7; margin: 2em 0;" />
          ${content}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 500);
  };

  const downloadMarkdown = () => {
    const blob = new Blob([notes], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${videoTitle || 'notes'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!url.trim()) return;

    setStatus('processing');
    setProgress('Submitting job...');
    setNotes('');
    setChatMessages([]);

    try {
      const payload = {
        url,
        provider,
        start_time: startTime || null,
        end_time: endTime || null,
        whisper_provider: whisperProvider,
        groq_api_key: groqApiKey || null
      };
      
      const res = await axios.post(`${API_BASE}/process`, payload);
      setTaskId(res.data.task_id);
    } catch (err) {
      setStatus('error');
      setProgress('Failed to connect to backend.');
      console.error(err);
    }
  };

  const handleChat = async (e) => {
    e.preventDefault();
    if (!currentQuestion.trim() || !taskId) return;

    const newMsg = { id: Date.now(), role: 'user', text: currentQuestion };
    setChatMessages(prev => [...prev, newMsg]);
    setCurrentQuestion('');
    setIsChatting(true);

    try {
      const res = await axios.post(`${API_BASE}/chat`, {
        task_id: taskId,
        question: newMsg.text
      });
      setChatMessages(prev => [...prev, { id: Date.now(), role: 'assistant', text: res.data.answer }]);
    } catch (err) {
      const errorMsg = err.response?.data?.detail || err.message || 'Sorry, I encountered an error connecting to the RAG engine.';
      setChatMessages(prev => [...prev, { id: Date.now(), role: 'assistant', text: `⚠️ Error: ${errorMsg}` }]);
    } finally {
      setIsChatting(false);
    }
  };

  return (
    <div className="min-h-screen bg-zinc-900 text-zinc-100 font-sans selection:bg-emerald-500/30">
      {/* Navbar */}
      <nav className="border-b border-white/5 bg-zinc-900/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-emerald-500 to-teal-500 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <h1 className="text-xl font-bold tracking-tight bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">
            VideoNotes Agent
          </h1>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 py-8">
        {/* Input Section */}
        {status !== 'completed' && (
          <div className="max-w-2xl mx-auto mt-12 mb-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="text-center mb-10">
              <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4 leading-tight">
                Turn any long video into <br />
                <span className="bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">
                  Intelligent Notes.
                </span>
              </h2>
              <p className="text-zinc-400 text-lg max-w-xl mx-auto">
                Paste a YouTube URL, extract exactly what you need, and ask follow-up questions directly to the video.
              </p>
            </div>

            <Card className="bg-zinc-800/50 border-white/10 shadow-2xl backdrop-blur-md">
              <CardContent className="p-6">
              <form onSubmit={handleGenerate}>
                <div className="relative mb-4">
                  <Youtube className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 w-5 h-5 z-10" />
                  <Input
                    type="url"
                    placeholder="https://youtube.com/watch?v=..."
                    className="w-full bg-zinc-900/50 border-white/5 rounded-xl py-6 pl-12 pr-4 text-zinc-100 placeholder:text-zinc-500 text-lg focus-visible:ring-emerald-500/50"
                    value={url}
                    onChange={e => setUrl(e.target.value)}
                    disabled={status === 'processing'}
                    required
                  />
                </div>

              <div className="mb-6">
                  <Button
                    type="button"
                    variant="ghost"
                    onClick={() => setShowSettings(!showSettings)}
                    className="flex items-center gap-2 text-sm text-zinc-400 hover:text-zinc-200 transition-colors px-0 hover:bg-transparent"
                  >
                    <Settings2 className="w-4 h-4" />
                    {showSettings ? 'Hide Advanced Settings' : 'Advanced Settings (Timestamps, Models)'}
                  </Button>

                  {showSettings && (
                    <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-6 animate-in slide-in-from-top-2 duration-300">
                      <div className="space-y-4">
                        <div className="space-y-2">
                          <Label className="uppercase tracking-wider text-zinc-400 text-xs">Analysis AI Model</Label>
                          <Select value={provider} onValueChange={setProvider} disabled={status === 'processing'}>
                            <SelectTrigger className="w-full bg-zinc-900 border-white/10 text-zinc-100 h-11">
                              <SelectValue placeholder="Select Model" />
                            </SelectTrigger>
                            <SelectContent className="bg-zinc-900 border-white/10 text-zinc-100">
                              <SelectItem value="gemini">Google Gemini 2.5 Flash</SelectItem>
                              <SelectItem value="anthropic">Anthropic Claude 3.5 Sonnet</SelectItem>
                              <SelectItem value="ollama">Ollama (Local)</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label className="uppercase tracking-wider text-zinc-400 text-xs">Audio Transcription Engine</Label>
                          <Select value={whisperProvider} onValueChange={setWhisperProvider} disabled={status === 'processing'}>
                            <SelectTrigger className="w-full bg-zinc-900 border-white/10 text-zinc-100 h-11">
                              <SelectValue placeholder="Select Engine" />
                            </SelectTrigger>
                            <SelectContent className="bg-zinc-900 border-white/10 text-zinc-100">
                              <SelectItem value="local">Local Whisper (CPU/GPU)</SelectItem>
                              <SelectItem value="groq">Groq Faster Whisper (Cloud API)</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                      
                      <div className="space-y-4">
                        <div className="space-y-2">
                          <Label className="flex items-center gap-2 uppercase tracking-wider text-zinc-400 text-xs">
                              <Clock className="w-3 h-3" /> Timestamp Range (Optional)
                          </Label>
                          <div className="flex items-center gap-2">
                            <Input
                              type="text"
                              placeholder="00:00"
                              className="bg-zinc-900 border-white/10 text-center h-11"
                              value={startTime}
                              onChange={e => setStartTime(e.target.value)}
                            />
                            <span className="text-zinc-500">to</span>
                            <Input
                              type="text"
                              placeholder="05:30"
                              className="bg-zinc-900 border-white/10 text-center h-11"
                              value={endTime}
                              onChange={e => setEndTime(e.target.value)}
                            />
                          </div>
                          <p className="text-[10px] text-zinc-500 mt-1">Use MM:SS format to process only a specific part of the video.</p>
                        </div>

                        {whisperProvider === 'groq' && (
                          <div className="space-y-2 animate-in fade-in duration-300">
                            <Label className="uppercase tracking-wider text-teal-400 text-xs shadow-sm">Groq API Key (Required for Groq Whisper)</Label>
                            <Input
                                type="password"
                                placeholder="gsk_..."
                                className="bg-zinc-900 border-teal-500/30 text-zinc-100 h-11 focus-visible:ring-teal-500/50"
                                value={groqApiKey}
                                onChange={e => setGroqApiKey(e.target.value)}
                                disabled={status === 'processing'}
                                required={whisperProvider === 'groq'}
                            />
                            <p className="text-[10px] text-zinc-500 mt-1">Extremely fast cloud transcription. Accepts up to ~25MB files.</p>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>

                <Button
                  type="submit"
                  disabled={status === 'processing'}
                  className="w-full bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 text-white font-semibold py-6 rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-500/25 border-none h-auto text-base"
                >
                  {status === 'processing' ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      <span>Processing ({progress})...</span>
                    </>
                  ) : (
                    <>
                      <Play className="w-5 h-5 fill-current" />
                      <span>Generate Intelligent Notes</span>
                    </>
                  )}
                </Button>

                {status === 'error' && (
                  <div className="mt-4 p-4 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
                    {progress}
                  </div>
                )}
              </form>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Results Section */}
        {status === 'completed' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start fade-in duration-700">
            
            {/* Left Column: Metadata & Notes */}
            <div className="lg:col-span-8 space-y-6">
              
              <Card className="bg-zinc-800/40 border-white/10 backdrop-blur-md">
                <CardHeader className="flex flex-col sm:flex-row items-start justify-between gap-4 space-y-0">
                  <div className="flex items-start gap-4">
                    <div className="p-3 bg-emerald-500/10 rounded-xl border border-emerald-500/20">
                      <FileText className="w-6 h-6 text-emerald-400" />
                    </div>
                    <div>
                      <CardTitle className="text-2xl font-bold text-white mb-2 leading-tight">{videoTitle}</CardTitle>
                      <CardDescription className="text-sm text-zinc-400 line-clamp-3 leading-relaxed">
                        {videoDescription || "No description provided."}
                      </CardDescription>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={downloadMarkdown} className="bg-zinc-900 border-white/10 text-zinc-300 hover:text-white cursor-pointer hover:bg-zinc-800">
                      <FileCode2 className="w-4 h-4 mr-2" /> Markdown
                    </Button>
                    <Button variant="outline" size="sm" onClick={downloadPDF} className="bg-zinc-900 border-white/10 text-zinc-300 hover:text-white cursor-pointer hover:bg-zinc-800">
                      <FileDown className="w-4 h-4 mr-2" /> PDF
                    </Button>
                  </div>
                </CardHeader>
              </Card>

              {/* Notes Content */}
              <div id="notes-content" className="bg-zinc-900 border border-white/10 rounded-2xl p-8 shadow-xl prose prose-invert prose-indigo max-w-none">
                <ReactMarkdown>{notes}</ReactMarkdown>
              </div>
            </div>

            {/* Right Column: AI Chat for RAG */}
            <Card className="lg:col-span-4 sticky top-24 bg-zinc-800/80 border-white/10 flex flex-col h-[600px] shadow-xl backdrop-blur-xl overflow-hidden p-0">
              <div className="p-5 border-b border-white/10 bg-zinc-800/50 flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-teal-500/20 flex items-center justify-center border border-teal-500/30">
                  <Bot className="w-4 h-4 text-teal-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white tracking-tight">Q&A Chat</h3>
                  <p className="text-xs text-zinc-400">Ask questions about the video</p>
                </div>
              </div>

              <ScrollArea className="flex-1 p-5">
                <div className="space-y-4 pr-4 pb-4">
                  {chatMessages.length === 0 && (
                    <div className="h-full flex flex-col items-center justify-center text-center text-zinc-500 space-y-3 mt-10">
                      <MessageSquare className="w-8 h-8 opacity-50" />
                      <p className="text-sm px-4">Don't understand a concept? Ask follow-up questions to query the video directly.</p>
                    </div>
                  )}
                  {chatMessages.map((msg) => (
                    <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                      <div className={`max-w-[85%] rounded-2xl p-4 text-sm leading-relaxed ${
                        msg.role === 'user' 
                          ? 'bg-emerald-600 text-white rounded-tr-sm' 
                          : 'bg-zinc-700/50 text-zinc-200 border border-white/5 rounded-tl-sm'
                      }`}>
                        {msg.role === 'assistant' ? <ReactMarkdown>{msg.text}</ReactMarkdown> : msg.text}
                      </div>
                    </div>
                  ))}
                  {isChatting && (
                    <div className="flex justify-start">
                      <div className="bg-zinc-700/50 border border-white/5 rounded-2xl rounded-tl-sm p-4 w-16 flex items-center justify-center gap-1.5 h-[52px]">
                        <div className="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                        <div className="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                        <div className="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce"></div>
                      </div>
                    </div>
                  )}
                  <div ref={chatEndRef} />
                </div>
              </ScrollArea>

              <div className="p-4 bg-zinc-800/90 border-t border-white/10">
                <form onSubmit={handleChat} className="relative flex gap-2">
                  <Input
                    type="text"
                    placeholder="Ask about timestamps, concepts, etc..."
                    value={currentQuestion}
                    onChange={(e) => setCurrentQuestion(e.target.value)}
                    disabled={isChatting}
                    className="w-full bg-zinc-900 border-white/10 rounded-xl py-5 pl-4 pr-12 text-sm text-white placeholder:text-zinc-500 focus-visible:ring-teal-500/50"
                  />
                  <Button 
                    type="submit" 
                    size="icon"
                    disabled={isChatting || !currentQuestion.trim()}
                    className="absolute right-2 top-1/2 -translate-y-1/2 bg-teal-500/20 text-teal-400 hover:bg-teal-500/30 hover:text-teal-300 rounded-lg transition-colors border-none"
                  >
                    <Send className="w-4 h-4" />
                  </Button>
                </form>
              </div>
            </Card>
            
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
