services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: contentpilot-searxng
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/

  backend:
    build: .
    container_name: contentpilot-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - searxng
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:6739/contentpilot
      - SEARXNG_URL=http://searxng:8080
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: contentpilot-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
