"""
NotesSynthesizer - Converts analyzed chunks into final structured notes.
"""

import json
from datetime import timedelta
from typing import List

import litellm

from analyzer import AnalyzedChunk
from config import Config
from note_structuring import StructuredSection, structure_analyzed_chunks


class NotesSynthesizer:
    """Synthesizes analyzed chunks into final notes."""

    def __init__(self, config: Config):
        self.config = config

    def synthesize(
        self,
        chunks: List[AnalyzedChunk] | List[StructuredSection],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        structured_sections = self._ensure_sections(chunks)
        if self.config.output_format == "json":
            return self._synthesize_json(structured_sections, video_title, total_duration_seconds)
        return self._synthesize_markdown(structured_sections, video_title, total_duration_seconds)

    def _ensure_sections(
        self, items: List[AnalyzedChunk] | List[StructuredSection]
    ) -> List[StructuredSection]:
        if not items:
            return []
        first = items[0]
        if isinstance(first, StructuredSection):
            return items  # type: ignore[return-value]
        return structure_analyzed_chunks(items)  # type: ignore[arg-type]

    def _synthesize_markdown(
        self,
        sections: List[StructuredSection],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        prompt = self.build_markdown_prompt(sections, video_title, total_duration_seconds)
        duration_str = str(timedelta(seconds=int(total_duration_seconds)))
        print("\n=== VideoNotes Synthesis Prompt ===")
        print(prompt)
        print("=== End Synthesis Prompt ===\n")

        response = litellm.completion(
            model=self.config.current_model,
            max_tokens=self.config.max_tokens_synthesis,
            messages=[{"role": "user", "content": prompt}],
        )

        notes = response.choices[0].message.content.strip()
        notes += f"\n\n---\n*Generated by VideoNotes · {len(sections)} sections · {duration_str} video*\n"
        return notes

    def build_markdown_prompt(
        self,
        sections: List[StructuredSection],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        extracted_data = self._build_extraction_summary(sections)
        duration_str = str(timedelta(seconds=int(total_duration_seconds)))
        custom_instruction = (
            f"\nAdditional user instructions:\n{self.config.custom_prompt_template.strip()}\n"
            if self.config.custom_prompt_template
            else ""
        )

        summary_heading = self._summary_heading_instruction()
        return f"""You are creating structured study notes from a video.

## Video: "{video_title}"
Duration: {duration_str}

## Extracted Content:
{extracted_data}

---

## Your Task:
Create clean, well-structured Markdown notes from this extracted content.

Rules:
- Organize by topic, not by raw timestamp order unless chronology is essential.
- Group related ideas from different moments together.
- Start with a 2-3 sentence {summary_heading} at the top.
- Use ## headers for major topics and ### for sub-topics.
- Use bullet points for key points.
- Bold important terms or concepts.
- For concepts/definitions, format as: **Term** - definition
- Put action items in a dedicated ## Action Items section at the end when relevant.
- {self.config.detail_instruction}
- Style mode: {self.config.note_style}
- {self._note_style_instruction()}
- {self._timestamp_instruction()}
{custom_instruction}

Output clean Markdown only. Start with a # heading using the video title."""

    def _synthesize_json(
        self,
        sections: List[StructuredSection],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        output = {
            "title": video_title,
            "duration_seconds": total_duration_seconds,
            "sections": [],
            "all_concepts": [],
            "all_action_items": [],
        }

        for section in sections:
            output["sections"].append(
                {
                    "title": section.title,
                    "timestamps": section.timestamps,
                    "key_points": section.key_points,
                    "concepts": section.concepts,
                    "action_items": section.action_items,
                }
            )
            output["all_concepts"].extend(section.concepts)
            output["all_action_items"].extend(section.action_items)

        output["all_concepts"] = list(dict.fromkeys(output["all_concepts"]))
        output["all_action_items"] = list(dict.fromkeys(output["all_action_items"]))
        return json.dumps(output, indent=2, ensure_ascii=False)

    def _build_extraction_summary(self, sections: List[StructuredSection]) -> str:
        lines = []
        for section in sections:
            timestamp_text = ", ".join(section.timestamps[:3]) or "no timestamps"
            lines.append(f"\n### {section.title} ({timestamp_text})")
            for point in section.key_points:
                lines.append(f"- {point}")
            for concept in section.concepts:
                lines.append(f"  Concept: {concept}")
            for action in section.action_items:
                lines.append(f"  Action: {action}")
        return "\n".join(lines)

    def _note_style_instruction(self) -> str:
        instructions = {
            "study_notes": "Prioritize teaching clarity, important definitions, and key explanations.",
            "executive_summary": "Prioritize high-signal takeaways, business context, and decisions.",
            "meeting_notes": "Capture agenda, decisions, owners, open questions, and next steps.",
            "tutorial_breakdown": "Present the content as a step-by-step walkthrough with ordered guidance.",
            "actionable_checklist": "Favor concrete actions, tasks, and checklists over long exposition.",
            "revision_notes": "Compress ideas into concise revision-ready notes with recall cues.",
        }
        return instructions.get(self.config.note_style, instructions["study_notes"])

    def _timestamp_instruction(self) -> str:
        if self.config.include_timestamps:
            return "Include [MM:SS] timestamps inline after specific points."
        return "Do not include timestamps."

    def _summary_heading_instruction(self) -> str:
        if self.config.note_style == "executive_summary":
            return "Executive Summary section"
        return "Overview section"
