"""
NotesSynthesizer - Converts analyzed chunks into final structured notes.

Does two things:
1. Groups chunks by inferred topic sections
2. Calls Claude one final time to synthesize everything into
   a coherent, well-structured notes document
"""

import json
from typing import List, Dict
from datetime import timedelta

import litellm

from config import Config
from analyzer import AnalyzedChunk


class NotesSynthesizer:
    """Synthesizes analyzed chunks into final notes."""

    def __init__(self, config: Config):
        self.config = config

    def synthesize(
        self,
        chunks: List[AnalyzedChunk],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        """
        Produce final notes from all analyzed chunks.
        Returns markdown string.
        """
        # Filter to relevant chunks only
        relevant = [c for c in chunks if c.classification == "CORE"]
        if not relevant:
            # Fallback: include everything
            relevant = chunks

        if self.config.output_format == "json":
            return self._synthesize_json(relevant, video_title, total_duration_seconds)
        else:
            return self._synthesize_markdown(relevant, video_title, total_duration_seconds)

    def _synthesize_markdown(
        self,
        chunks: List[AnalyzedChunk],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        """Use Claude to produce the final markdown notes."""

        # Build a compact representation of all extracted data
        extracted_data = self._build_extraction_summary(chunks)

        duration_str = str(timedelta(seconds=int(total_duration_seconds)))

        prompt = f"""You are creating structured study notes from a video.

## Video: "{video_title}"
Duration: {duration_str}

## Extracted Content (from AI analysis of each ~2-minute chunk):
{extracted_data}

---

## Your Task:
Create clean, well-structured Markdown notes from this extracted content.

Rules:
- Organize by TOPIC, not by time order (unless time order is the natural structure)
- Group related points from different timestamps together
- Write a 2-3 sentence **Executive Summary** at the top
- Use `##` headers for main topics, `###` for sub-topics
- Use bullet points for key points
- **Bold** important terms or concepts
- For concepts/definitions, format as: **Term** — definition
- For action items, use a separate `## Action Items` section at the end
- If timestamps are enabled, add `[MM:SS]` inline after key points that come from specific moments
- Do NOT include filler, jokes, or sponsor content
- Write notes that a student would actually want to read
- {self.config.detail_instruction}

{f'Include timestamps like [MM:SS] after specific points.' if self.config.include_timestamps else 'Do not include timestamps.'}

Output clean Markdown only. Start with a `# {video_title}` heading."""

        response = litellm.completion(
            model=self.config.current_model,
            max_tokens=self.config.max_tokens_synthesis,
            messages=[{"role": "user", "content": prompt}],
        )

        notes = response.choices[0].message.content.strip()

        # Append metadata footer
        pruned = sum(1 for _ in range(len(chunks)))  # Already filtered to CORE
        notes += f"\n\n---\n*Generated by VideoNotes · {len(chunks)} core segments · {duration_str} video*\n"

        return notes

    def _synthesize_json(
        self,
        chunks: List[AnalyzedChunk],
        video_title: str,
        total_duration_seconds: float,
    ) -> str:
        """Produce JSON-structured output."""
        output = {
            "title": video_title,
            "duration_seconds": total_duration_seconds,
            "sections": [],
            "all_concepts": [],
            "all_action_items": [],
        }

        # Group by section title
        sections: Dict[str, dict] = {}
        for chunk in chunks:
            title = chunk.section_title or "General"
            if title not in sections:
                sections[title] = {
                    "title": title,
                    "timestamps": [],
                    "key_points": [],
                    "concepts": [],
                    "action_items": [],
                }
            s = sections[title]
            s["timestamps"].append(f"{chunk.start_timestamp}–{chunk.end_timestamp}")
            s["key_points"].extend(chunk.key_points)
            s["concepts"].extend(chunk.concepts)
            s["action_items"].extend(chunk.action_items)

            output["all_concepts"].extend(chunk.concepts)
            output["all_action_items"].extend(chunk.action_items)

        output["sections"] = list(sections.values())
        # Deduplicate
        output["all_concepts"] = list(dict.fromkeys(output["all_concepts"]))
        output["all_action_items"] = list(dict.fromkeys(output["all_action_items"]))

        return json.dumps(output, indent=2, ensure_ascii=False)

    def _build_extraction_summary(self, chunks: List[AnalyzedChunk]) -> str:
        """Build a compact text summary of extracted data for the synthesis prompt."""
        lines = []

        for chunk in chunks:
            lines.append(f"\n### [{chunk.start_timestamp}–{chunk.end_timestamp}]"
                         + (f" — {chunk.section_title}" if chunk.section_title else ""))

            if chunk.key_points:
                for pt in chunk.key_points:
                    lines.append(f"- {pt}")

            if chunk.concepts:
                for c in chunk.concepts:
                    lines.append(f"  📌 Concept: {c}")

            if chunk.action_items:
                for a in chunk.action_items:
                    lines.append(f"  ✅ Action: {a}")

        return "\n".join(lines)
